name: Simple Publish to Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
      
      - name: Build extension
        run: npm run compile
      
      - name: Install vsce
        run: npm install -g @vscode/vsce
      
      - name: Package extension
        run: vsce package --no-dependencies
      
      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: visual-code-map-vsix
          path: '*.vsix'