name: Publish to VS Code Marketplace

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to marketplace'
        required: true
        default: 'yes'
        type: choice
        options:
          - yes
          - no

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      # Skip linter and tests for now to publish quickly
      # - name: Run linter
      #   run: npm run lint
      
      # - name: Run tests
      #   run: npm test
      
      - name: Build extension
        run: npm run compile

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build extension
        run: npm run compile
      
      - name: Install vsce
        run: npm install -g @vscode/vsce
      
      - name: Package extension
        run: vsce package
      
      - name: Publish to Marketplace
        if: github.event.inputs.publish == 'yes'
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: visual-code-map-vsix
          path: '*.vsix'
      
      - name: Create GitHub Release
        if: github.event.inputs.publish == 'yes'
        uses: softprops/action-gh-release@v1
        with:
          files: '*.vsix'
          body: |
            ## Visual Code Map Release
            
            ### Installation
            1. Download the `.vsix` file from the assets below
            2. In VS Code, run "Extensions: Install from VSIX..." from the command palette
            3. Select the downloaded file
            
            ### Marketplace
            Also available on the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=prawal-sharma.visual-code-map)
            
            See [CHANGELOG.md](https://github.com/Prawal-Sharma/VisualCodeMap/blob/main/CHANGELOG.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}